{{- if .Values.dnsmasq.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  labels:
    app: dnsmasq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      hostNetwork: true
      containers:
      - image: {{ .Values.dnsmasq.image.registry }}/{{ .Values.dnsmasq.image.repository }}:{{ tpl .Values.dnsmasq.image.tag . }}
        name: dnsmasq
        ports:
        - containerPort: 53
          hostPort: 53
          protocol: UDP
        - containerPort: 53
          hostPort: 53
          protocol: TCP
        - containerPort: 67
          hostPort: 67
          protocol: UDP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - mountPath: /etc/dnsmasq.conf
          name: dnsmasq
          subPath: mounts/dnsmasq.conf
        - mountPath: /var/lib/tftpboot
          name: pxe
        - mountPath: /var/lib/tftpboot/pxelinux.cfg
          name: pxelinux-cfg-default
      hostNetwork: true
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: config
            path: mounts/dnsmasq.conf
          name: dnsmasq
        name: dnsmasq
      - configMap:
          defaultMode: 420
          name: pxelinux-cfg-default
        name: pxelinux-cfg-default
      - name: pxe
        secret:
          secretName: pxe
{{- end }}
