{{- if .Values.dnsmasq.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: "dnsmasq"
spec:
  type: ClusterIP
  ports:
  - port: 67
    name: dhcp-udp
    targetPort: 67
    protocol: UDP
  - port: 53
    name: dns-udp
    targetPort: 53
    protocol: UDP
  - port: 53
    name: dhcp-tcp
    targetPort: 53
    protocol: TCP
  selector:
    app: "dnsmasq"
{{- end }}
