{{- if .Values.dnsmasq.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: dnsmasq
data:
  config: |-
{{ .Values.dnsmasq.config | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: pxelinux-cfg-default
data:
  default: |- 
    DEFAULT pxeboot
    TIMEOUT 20
    PROMPT 0
    LABEL pxeboot
        KERNEL http://<HTTP_server>/rhcos-<version>-live-kernel-<architecture> 
        APPEND initrd=http://<HTTP_server>/rhcos-<version>-live-initramfs.<architecture>.img coreos.live.rootfs_url=http://<HTTP_server>/rhcos-<version>-live-rootfs.<architecture>.img coreos.inst.install_dev=/dev/sda coreos.inst.ignition_url=http://<HTTP_server>/bootstrap.ign  
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: pxelinux-cfg-default
data:
  ldlinux.c32: |-
{{ .Files.Get "files/pxe/ldlinux.c32" | indent 4}}
  menu.c32: |-
{{ .Files.Get "files/pxe/menu.c32" | indent 4}}
  pxelinux.0: |-
{{ .Files.Get "files/pxe/pxelinux.0" | indent 4}}
{{- end}}
