{{- if .Values.dnsmasq.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: dnsmasq
data:
  config: |-
{{ .Values.dnsmasq.config | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: pxelinux-cfg-default
data:
  default: |- 
{{ .Values.dnsmasq.default | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: pxelinux-cfg-default
data:
  ldlinux.c32: |-
{{ .Files.Get "files/pxe/ldlinux.c32" | indent 4}}
  menu.c32: |-
{{ .Files.Get "files/pxe/menu.c32" | indent 4}}
  pxelinux.0: |-
{{ .Files.Get "files/pxe/pxelinux.0" | indent 4}}
{{- end}}
