# Need to use a secret here else Helm gives the error "error converting YAML to JSON: yaml: control characters are not allowed"

{{- if .Values.dnsmasq.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  name: pxe
data:
  ldlinux.c32: |-
    {{ .Files.Get "files/pxe/ldlinux.c32" | b64enc }}
  menu.c32: |-
    {{ .Files.Get "files/pxe/menu.c32" | b64enc}}
  pxelinux.0: |-
    {{ .Files.Get "files/pxe/pxelinux.0" | b64enc }}
{{- end}}
