{{- if .Values.haproxy.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      hostNetwork: true
      containers:
      - name: haproxy
        image: {{ .Values.haproxy.image.registry }}/{{ .Values.haproxy.image.repository }}:{{ tpl .Values.haproxy.image.tag . }}
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: tcp
        - containerPort: 6443
          protocol: tcp
        - containerPort: 22623
          protocol: tcp
        - containerPort: 9000
          protocol: tcp
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
          - name: haproxy
            mountPath: /etc/haproxy.conf
            subPath: mounts/haproxy.conf
      volumes:
        - name: haproxy
          configMap:
            name: haproxy
            items:
             - key: config
               path: mounts/haproxy.conf

{{- end }}
