{{- if .Values.nginx.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - image: {{ .Values.nginx.image.registry }}/{{ .Values.nginx.image.repository }}:{{ tpl .Values.nginx.image.tag . }}
        name: nginx
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
          - name: nginx
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: mounts/default.conf
      hostNetwork: true
      volumes:
        - name: nginx
          configMap:
            name: nginx
            items:
             - key: config
               path: mounts/default.conf
{{- end }}


