
# Grafana Letsencrypt
{{- if .Values.lsdobserve.letsencrypt -}}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana-ingress-letsencrypt
spec:
  commonName: {{ .Values.lsdobserve.grafana.ingress.url }}
  secretName: grafana.ingress-letsencrypt
  issuerRef:
    name: {{ .Values.lsdobserve.letsencryptIssuer }}
{{- end }}