dhcpserver:
  enabled: true
  image:
    registry: "docker.io"
    repository: "networkboot/dhcpd"
    tag: "1.1.0"
  # Below is a standard dhcpd.conf configuration. Modify appropriately
  config: |
    subnet 10.1.0.0 netmask 255.255.255.240 {
      range 10.1.0.2 10.1.0.13;
      option routers 10.1.0.14;
    
      host bootstrap-01 {
        hardware ethernet 00:50:56:01:15:96;
        option host-name "bootstrap-01.lab-01.okd.lsdopen.io";
        fixed-address 10.1.0.2;
      }
      host controlplane-01 {
        hardware ethernet 00:50:56:01:15:97;
        option host-name "controlplane-01.lab-01.okd.lsdopen.io";
        fixed-address 10.1.0.3;
      }
    
      deny unknown-clients;
    }

dnsmasq:
  enabled: true
  image:
    registry: "docker.io"
    repository: "lsdopen/dnsmasq-docker"
    tag: "latest"
  # Below is a standard dhcpd.conf configuration. Modify appropriately
  config: |
    bogus-priv
    filterwin2k
    expand-hosts
    domain=lab-01.okd.lsdopen.io
    local=/lab-01.okd.lsdopen.io/
    domain-needed
    bind-interfaces

    # DHCP & DNS & PTR
    log-dhcp
    dhcp-authoritative
    ## Gateway
    dhcp-option=option:router,10.1.0.14
    ## The IP address of the Bastion (this server)
    dhcp-option=option:dns-server,10.1.0.1
    ## Statically assigned IP addresses
    dhcp-range=10.1.0.2,10.1.0.10,255.255.255.240,12h
    dhcp-host=10.1.0.2,00:50:56:01:15:96,bootstrap-01,24h
    ptr-record=2.0.1.10.in-addr.arpa.,"bootstrap-01"
    address=/bootstrap-01/10.1.0.2
