# Values for Kubernetes
ahoyHost: ahoy.k8s.host
ahoyClusterType: kubernetes
ahoyRedirectUri: http://ahoy.k8s.host/
authIssuer: http://ahoy-keycloak-http.ahoy.svc/auth/realms/Ahoy
authFrontendIssuer: https://keycloak.k8s.host/auth/realms/Ahoy

postgresql:
  ## PostgreSQL user (has superuser privileges if username is `postgres`)
  ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
  postgresqlUsername: postgres

  ## PostgreSQL password
  ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  postgresqlPassword: ahoy123456

  ## Create a database
  ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#creating-a-database-on-first-run
  ##
  postgresqlDatabase: ahoy

keycloak:
  # Additional environment variables for Keycloak
  extraEnv: |
    - name: KEYCLOAK_IMPORT
      value: /tmp/ahoy/ahoy-realm.json
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: admin
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

  # Add additional volumes, e. g. for custom themes
  extraVolumes: |
    - name: ahoy-realm
      configMap:
        name: ahoy-keycloak-realm

  # Add additional volumes mounts, e. g. for custom themes
  extraVolumeMounts: |
    - name: ahoy-realm
      mountPath: "/tmp/ahoy"

  ingress:
    # If `true`, an Ingress is created
    enabled: true
    # The Service port targeted by the Ingress
    servicePort: http
    # Ingress annotations
    annotations: {}
    # Additional Ingress labels
    labels: {}
    # List of rules for the Ingress
    rules:
      -
        # Ingress host
        host: 'keycloak.k8s.host'
        # Paths for the host
        paths:
          - /
    # TLS configuration
    tls:
      - hosts:
          - keycloak.k8s.host
        secretName: keycloak-tls

  postgresql:
    fullnameOverride: keycloak-postgresql

    # If `true`, the Postgresql dependency is enabled
    enabled: true
    # PostgreSQL User to create
    postgresqlUsername: keycloak
    # PostgreSQL Password for the new user
    postgresqlPassword: keycloak
    # PostgreSQL Database to create
    postgresqlDatabase: keycloak
    # Persistent Volume Storage configuration