apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ahoy-server
  name: ahoy-server
  namespace: ahoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ahoy-server
  template:
    metadata:
      labels:
        app: ahoy-server
    spec:
      serviceAccountName: ahoy
      volumes:
        - name: properties-prod
          configMap:
            name: ahoy-properties-prod
      containers:
        - image: openlsd/ahoy:{{ .Chart.Version }}
          imagePullPolicy: Always
          name: ahoy-server
          env:
          - name: AHOY_HOST
            value: '{{ .Values.ahoyHost }}'
          - name: AHOY_CLUSTER_TYPE
            value: '{{ .Values.ahoyClusterType }}'
          - name: AHOY_AUTH_ISSUER
            value: '{{ .Values.authIssuer }}'
          - name: AHOY_UI_AUTH_ISSUER
            value: '{{ .Values.authFrontendIssuer }}'
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: properties-prod
              mountPath: "/tmp/config"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources: {}
